name: Pilot Test

on:
  workflow_dispatch:

jobs:
  pilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Run pilot export
        run: node scripts/auto_export.mjs reports/test_samples/sample_pilot.csv --project PilotProject --out-dir reports/staging_output --qr-url "https://example.com/pilot"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pilot-reports
          path: reports/staging_output
