name: Smoke Report

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          cd reporting
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run report
        run: |
          cd reporting
          python export_report.py --out-dir ./output_ci
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: report-artifacts
          path: reporting/output_ci/**
